package elokuva.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import elokuva.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.03.07 19:06:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ArvostelutTest {



  // Generated by ComTest BEGIN
  /** testAnnaArvostelut29 */
  @Test
  public void testAnnaArvostelut29() {    // Arvostelut: 29
    Arvostelut arvostelut = new Arvostelut(); 
    Arvostelu arvostelu1  = new Arvostelu(1); arvostelut.lisaa(arvostelu1); 
    Arvostelu arvostelu2  = new Arvostelu(3); arvostelut.lisaa(arvostelu2); 
    Arvostelu arvostelu13 = new Arvostelu(1); arvostelut.lisaa(arvostelu13); 
    Arvostelu arvostelu14 = new Arvostelu(1); arvostelut.lisaa(arvostelu14); 
    Arvostelu arvostelu15 = new Arvostelu(2); arvostelut.lisaa(arvostelu15); 
    Arvostelu arvostelu16 = new Arvostelu(2); arvostelut.lisaa(arvostelu16); 
    List<Arvostelu> loytyneet; 
    loytyneet = arvostelut.annaArvostelut(4); 
    assertEquals("From: Arvostelut line: 43", 0, loytyneet.size()); 
    loytyneet = arvostelut.annaArvostelut(3); 
    assertEquals("From: Arvostelut line: 45", 1, loytyneet.size()); 
    loytyneet = arvostelut.annaArvostelut(1); 
    assertEquals("From: Arvostelut line: 47", 3, loytyneet.size()); 
    assertEquals("From: Arvostelut line: 48", true, loytyneet.get(0) == arvostelu1); 
    assertEquals("From: Arvostelut line: 49", true, loytyneet.get(1) == arvostelu13); 
    loytyneet = arvostelut.annaArvostelut(2); 
    assertEquals("From: Arvostelut line: 51", 2, loytyneet.size()); 
    assertEquals("From: Arvostelut line: 52", true, loytyneet.get(0) == arvostelu15); 
    assertEquals("From: Arvostelut line: 53", false, loytyneet.get(0) == arvostelu1); 
  } // Generated by ComTest END
}