package elokuva.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import elokuva.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.03.07 19:06:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ArvosteluTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi68 */
  @Test
  public void testRekisteroi68() {    // Arvostelu: 68
    Arvostelu arv = new Arvostelu(); 
    assertEquals("From: Arvostelu line: 70", 0, arv.getTunnusNro()); 
    arv.rekisteroi(); 
    Arvostelu arv2 = new Arvostelu(); 
    arv2.rekisteroi(); 
    int n1 = arv.getTunnusNro(); 
    int n2 = arv2.getTunnusNro(); 
    assertEquals("From: Arvostelu line: 76", n2-1, n1); 
  } // Generated by ComTest END
}