package elokuva.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import elokuva.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.05.24 18:45:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ArvosteluTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi109 */
  @Test
  public void testRekisteroi109() {    // Arvostelu: 109
    Arvostelu arv = new Arvostelu(); 
    assertEquals("From: Arvostelu line: 111", 0, arv.getTunnusNro()); 
    arv.rekisteroi(); 
    Arvostelu arv2 = new Arvostelu(); 
    arv2.rekisteroi(); 
    int n1 = arv.getTunnusNro(); 
    int n2 = arv2.getTunnusNro(); 
    assertEquals("From: Arvostelu line: 117", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse146 */
  @Test
  public void testParse146() {    // Arvostelu: 146
    Arvostelu arv = new Arvostelu(); 
    arv.parse("   2 | 3   | 3 | 10 | asd"); 
    assertEquals("From: Arvostelu line: 149", 3, arv.getArvostelijanId()); 
    assertEquals("From: Arvostelu line: 150", "2|3|3|10|asd", arv.toString());
  } // Generated by ComTest END
}