package elokuva.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import elokuva.Arvostelu;
import elokuva.Arvostelut;
import elokuva.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.18 18:16:32 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ArvostelutTest {



  // Generated by ComTest BEGIN
  /** testPoistaElokuvanArvostelut38 */
  @Test
  public void testPoistaElokuvanArvostelut38() {    // Arvostelut: 38
    Arvostelut arvostelut = new Arvostelut(); 
    Arvostelu arv1 = new Arvostelu(); arv1.taytaArvostelu(1, 1); arvostelut.lisaa(arv1); 
    Arvostelu arv2 = new Arvostelu(); arv2.taytaArvostelu(1, 2); arvostelut.lisaa(arv2); 
    Arvostelu arv3 = new Arvostelu(); arv3.taytaArvostelu(2, 1); arvostelut.lisaa(arv3); 
    assertEquals("From: Arvostelut line: 46", 2, arvostelut.annaArvostelut(1).size()); 
    assertEquals("From: Arvostelut line: 47", 1, arvostelut.annaArvostelut(2).size()); 
    arvostelut.poistaElokuvanArvostelut(1);  // Remove reviews for movie ID 1
    assertEquals("From: Arvostelut line: 49", 0, arvostelut.annaArvostelut(1).size()); 
    assertEquals("From: Arvostelut line: 50", 1, arvostelut.annaArvostelut(2).size()); 
    arvostelut.poistaElokuvanArvostelut(2);  // Remove reviews for movie ID 2
    assertEquals("From: Arvostelut line: 52", 0, arvostelut.annaArvostelut(2).size()); 
    arvostelut.poistaElokuvanArvostelut(999);  // Non-existent ID
    assertEquals("From: Arvostelut line: 54", 0, arvostelut.annaArvostelut(1).size());  // No change
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaArvostelut73 */
  @Test
  public void testAnnaArvostelut73() {    // Arvostelut: 73
    Arvostelut arvostelut = new Arvostelut(); 
    Arvostelu arvostelu1  = new Arvostelu(1); arvostelut.lisaa(arvostelu1); 
    Arvostelu arvostelu2  = new Arvostelu(3); arvostelut.lisaa(arvostelu2); 
    Arvostelu arvostelu13 = new Arvostelu(1); arvostelut.lisaa(arvostelu13); 
    Arvostelu arvostelu14 = new Arvostelu(1); arvostelut.lisaa(arvostelu14); 
    Arvostelu arvostelu15 = new Arvostelu(2); arvostelut.lisaa(arvostelu15); 
    Arvostelu arvostelu16 = new Arvostelu(2); arvostelut.lisaa(arvostelu16); 
    List<Arvostelu> loytyneet; 
    loytyneet = arvostelut.annaArvostelut(4); 
    assertEquals("From: Arvostelut line: 87", 0, loytyneet.size()); 
    loytyneet = arvostelut.annaArvostelut(3); 
    assertEquals("From: Arvostelut line: 89", 1, loytyneet.size()); 
    loytyneet = arvostelut.annaArvostelut(1); 
    assertEquals("From: Arvostelut line: 91", 3, loytyneet.size()); 
    assertEquals("From: Arvostelut line: 92", true, loytyneet.get(0) == arvostelu1); 
    assertEquals("From: Arvostelut line: 93", true, loytyneet.get(1) == arvostelu13); 
    loytyneet = arvostelut.annaArvostelut(2); 
    assertEquals("From: Arvostelut line: 95", 2, loytyneet.size()); 
    assertEquals("From: Arvostelut line: 96", true, loytyneet.get(0) == arvostelu15); 
    assertEquals("From: Arvostelut line: 97", false, loytyneet.get(0) == arvostelu1); 
  } // Generated by ComTest END
}