package elokuva.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import elokuva.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.05.24 18:43:15 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ElokuvaTest {



  // Generated by ComTest BEGIN
  /** testLisaaElokuva71 */
  @Test
  public void testLisaaElokuva71() {    // Elokuva: 71
    Elokuva elokuva1 = new Elokuva(); 
    assertEquals("From: Elokuva line: 73", 0, elokuva1.getElokuvaId()); 
    elokuva1.lisaaElokuva(); 
    Elokuva elokuva2 = new Elokuva(); 
    elokuva2.lisaaElokuva(); 
    int n1 = elokuva1.getElokuvaId(); 
    int n2 = elokuva2.getElokuvaId(); 
    assertEquals("From: Elokuva line: 79", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse123 */
  @Test
  public void testParse123() {    // Elokuva: 123
    Elokuva elokuva = new Elokuva(); 
    elokuva.parse("      3 | Aku Ankka | 23"); 
    assertEquals("From: Elokuva line: 126", 3, elokuva.getElokuvaId()); 
    assertEquals("From: Elokuva line: 127", true, elokuva.toString().startsWith("3|Aku Ankka|23")); 
    elokuva.taytaValmisLeffa(); 
    int n = elokuva.getElokuvaId(); 
    elokuva.parse(""+(n+20));  //otetaan vain id
    elokuva.taytaValmisLeffa(); 
    assertEquals("From: Elokuva line: 133", n+20, elokuva.getElokuvaId()); 
  } // Generated by ComTest END
}