package elokuva.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import elokuva.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.18 18:10:14 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ElokuvatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa46 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa46() throws SailoException {    // Elokuvat: 46
    Elokuvat elokuvat = new Elokuvat(); 
    Elokuva elokuva1 = new Elokuva(), elokuva2 = new Elokuva(); 
    assertEquals("From: Elokuvat line: 50", 0, elokuvat.getLkm()); 
    elokuvat.lisaa(elokuva1); assertEquals("From: Elokuvat line: 51", 1, elokuvat.getLkm()); 
    elokuvat.lisaa(elokuva2); assertEquals("From: Elokuvat line: 52", 2, elokuvat.getLkm()); 
    elokuvat.lisaa(elokuva1); assertEquals("From: Elokuvat line: 53", 3, elokuvat.getLkm()); 
    assertEquals("From: Elokuvat line: 54", elokuva1, elokuvat.anna(0)); 
    assertEquals("From: Elokuvat line: 55", elokuva2, elokuvat.anna(1)); 
    assertEquals("From: Elokuvat line: 56", elokuva1, elokuvat.anna(2)); 
    assertEquals("From: Elokuvat line: 57", false, elokuvat.anna(1) == elokuva1); 
    assertEquals("From: Elokuvat line: 58", true, elokuvat.anna(1) == elokuva2); 
    try {
    assertEquals("From: Elokuvat line: 59", elokuva1, elokuvat.anna(3)); 
    fail("Elokuvat: 59 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    elokuvat.lisaa(elokuva1); assertEquals("From: Elokuvat line: 60", 4, elokuvat.getLkm()); 
    elokuvat.lisaa(elokuva1); assertEquals("From: Elokuvat line: 61", 5, elokuvat.getLkm()); 
    try {
    elokuvat.lisaa(elokuva1); 
    fail("Elokuvat: 62 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista118 
   * @throws SailoException when error
   */
  @Test
  public void testPoista118() throws SailoException {    // Elokuvat: 118
    Elokuvat elokuvat = new Elokuvat(); 
    Elokuva elokuva1 = new Elokuva(); elokuva1.lisaaElokuva();  // ID 1
    Elokuva elokuva2 = new Elokuva(); elokuva2.lisaaElokuva();  // ID 2
    Elokuva elokuva3 = new Elokuva(); elokuva3.lisaaElokuva();  // ID 3
    elokuvat.lisaa(elokuva1); elokuvat.lisaa(elokuva2); elokuvat.lisaa(elokuva3); 
    assertEquals("From: Elokuvat line: 125", 3, elokuvat.getLkm()); 
    elokuvat.poista(2);  // Remove movie with ID 2
    assertEquals("From: Elokuvat line: 127", 2, elokuvat.getLkm()); 
    assertEquals("From: Elokuvat line: 128", true, elokuvat.anna(0) == elokuva1); 
    assertEquals("From: Elokuvat line: 129", true, elokuvat.anna(1) == elokuva3); 
    try {
    elokuvat.anna(2); 
    fail("Elokuvat: 130 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    elokuvat.poista(999);  // Non-existent ID
    assertEquals("From: Elokuvat line: 132", 2, elokuvat.getLkm());  // No change
    elokuvat.poista(1);  // Remove first movie
    assertEquals("From: Elokuvat line: 134", 1, elokuvat.getLkm()); 
    assertEquals("From: Elokuvat line: 135", true, elokuvat.anna(0) == elokuva3); 
  } // Generated by ComTest END
}