package elokuva.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import elokuva.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.03.05 13:40:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ElokuvaTest {



  // Generated by ComTest BEGIN
  /** testLisaaElokuva61 */
  @Test
  public void testLisaaElokuva61() {    // Elokuva: 61
    Elokuva elokuva1 = new Elokuva(); 
    assertEquals("From: Elokuva line: 63", 0, elokuva1.getElokuvaId()); 
    elokuva1.lisaaElokuva(); 
    Elokuva elokuva2 = new Elokuva(); 
    elokuva2.lisaaElokuva(); 
    int n1 = elokuva1.getElokuvaId(); 
    int n2 = elokuva2.getElokuvaId(); 
    assertEquals("From: Elokuva line: 69", n2-1, n1); 
  } // Generated by ComTest END
}