package elokuva.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import elokuva.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.03.05 13:40:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ElokuvatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa38 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa38() throws SailoException {    // Elokuvat: 38
    Elokuvat elokuvat = new Elokuvat(); 
    Elokuva elokuva1 = new Elokuva(), elokuva2 = new Elokuva(); 
    assertEquals("From: Elokuvat line: 42", 0, elokuvat.getLkm()); 
    elokuvat.lisaa(elokuva1); assertEquals("From: Elokuvat line: 43", 1, elokuvat.getLkm()); 
    elokuvat.lisaa(elokuva2); assertEquals("From: Elokuvat line: 44", 2, elokuvat.getLkm()); 
    elokuvat.lisaa(elokuva1); assertEquals("From: Elokuvat line: 45", 3, elokuvat.getLkm()); 
    assertEquals("From: Elokuvat line: 46", elokuva1, elokuvat.anna(0)); 
    assertEquals("From: Elokuvat line: 47", elokuva2, elokuvat.anna(1)); 
    assertEquals("From: Elokuvat line: 48", elokuva1, elokuvat.anna(2)); 
    assertEquals("From: Elokuvat line: 49", false, elokuvat.anna(1) == elokuva1); 
    assertEquals("From: Elokuvat line: 50", true, elokuvat.anna(1) == elokuva2); 
    try {
    assertEquals("From: Elokuvat line: 51", elokuva1, elokuvat.anna(3)); 
    fail("Elokuvat: 51 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    elokuvat.lisaa(elokuva1); assertEquals("From: Elokuvat line: 52", 4, elokuvat.getLkm()); 
    elokuvat.lisaa(elokuva1); assertEquals("From: Elokuvat line: 53", 5, elokuvat.getLkm()); 
    try {
    elokuvat.lisaa(elokuva1); 
    fail("Elokuvat: 54 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}