package elokuva.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import elokuva.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.03.24 16:00:20 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KokoElokuvaTest {



  // Generated by ComTest BEGIN
  /** testAnnaArvostelut67 */
  @Test
  public void testAnnaArvostelut67() {    // KokoElokuva: 67
    KokoElokuva kokoelokuva = new KokoElokuva(); 
    Elokuva elokuva1 = new Elokuva(); Elokuva elokuva2 = new Elokuva(); Elokuva elokuva3 = new Elokuva(); 
    elokuva1.lisaaElokuva(); elokuva2.lisaaElokuva(); elokuva3.lisaaElokuva(); 
    int id1 = elokuva1.getElokuvaId(); 
    int id2 = elokuva2.getElokuvaId(); 
    Arvostelu arvostelu11 = new Arvostelu(id1); kokoelokuva.lisaa(arvostelu11); 
    Arvostelu arvostelu12 = new Arvostelu(id1); kokoelokuva.lisaa(arvostelu12); 
    Arvostelu arvostelu21 = new Arvostelu(id2); kokoelokuva.lisaa(arvostelu21); 
    Arvostelu arvostelu22 = new Arvostelu(id2); kokoelokuva.lisaa(arvostelu22); 
    Arvostelu arvostelu23 = new Arvostelu(id2); kokoelokuva.lisaa(arvostelu23); 
    List<Arvostelu> loytyneet; 
    loytyneet = kokoelokuva.annaArvostelut(elokuva3); 
    assertEquals("From: KokoElokuva line: 83", 0, loytyneet.size()); 
    loytyneet = kokoelokuva.annaArvostelut(elokuva1); 
    assertEquals("From: KokoElokuva line: 85", 2, loytyneet.size()); 
    assertEquals("From: KokoElokuva line: 86", true, loytyneet.get(0) == arvostelu11); 
    assertEquals("From: KokoElokuva line: 87", true, loytyneet.get(1) == arvostelu12); 
    loytyneet = kokoelokuva.annaArvostelut(elokuva2); 
    assertEquals("From: KokoElokuva line: 89", 3, loytyneet.size()); 
    assertEquals("From: KokoElokuva line: 90", true, loytyneet.get(0) == arvostelu21); 
  } // Generated by ComTest END
}