package elokuva.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import elokuva.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.03.27 17:10:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class NimimerkitTest {



  // Generated by ComTest BEGIN
  /** testAnnaNimet29 */
  @Test
  public void testAnnaNimet29() {    // Nimimerkit: 29
    Nimimerkit nimimerkit = new Nimimerkit(); 
    Nimimerkki nimi1 = new Nimimerkki(); nimi1.rekisteroi(); nimimerkit.lisaa(nimi1); 
    Nimimerkki nimi2 = new Nimimerkki(); nimi2.rekisteroi(); nimimerkit.lisaa(nimi2); 
    Nimimerkki nimi3 = new Nimimerkki(); nimi3.rekisteroi(); nimimerkit.lisaa(nimi3); 
    Nimimerkki nimi4 = new Nimimerkki(); nimi4.rekisteroi(); nimimerkit.lisaa(nimi4); 
    Nimimerkki nimi5 = new Nimimerkki(); nimi5.rekisteroi(); nimimerkit.lisaa(nimi5); 
    Nimimerkki nimi6 = new Nimimerkki(); nimi6.rekisteroi(); nimimerkit.lisaa(nimi6); 
    List<Nimimerkki> loytyneet; 
    loytyneet = nimimerkit.annaNimet(1); 
    assertEquals("From: Nimimerkit line: 43", 1, loytyneet.size()); 
    loytyneet = nimimerkit.annaNimet(2); 
    assertEquals("From: Nimimerkit line: 45", 1, loytyneet.size()); 
    loytyneet = nimimerkit.annaNimet(3); 
    assertEquals("From: Nimimerkit line: 47", 1, loytyneet.size()); 
    assertEquals("From: Nimimerkit line: 48", true, loytyneet.get(0) == nimi3); 
    assertEquals("From: Nimimerkit line: 49", false, loytyneet.get(0) == nimi2); 
    loytyneet = nimimerkit.annaNimet(3); 
    assertEquals("From: Nimimerkit line: 51", 1, loytyneet.size()); 
    assertEquals("From: Nimimerkit line: 52", true, loytyneet.get(0) == nimi3); 
    assertEquals("From: Nimimerkit line: 53", false, loytyneet.get(0) == nimi1); 
  } // Generated by ComTest END
}